version: 2
jobs:
  build:
    docker:
      - image: circleci/node
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: NPM Ignore
          command: 'sudo npm i -g npmignore'
      - run:
          name: Install Newman
          command: 'sudo npm install -g newman'
          
      - run:
          name: Working Dir
          command: 'ls -la'

      - run:
          name: API Testing
          command: 'newman run ./papi-test.postman_collection.json --environment ./papi-qa-test.postman_environment.json -r cli'
